site_name: OCA Documentation
site_url: https://oca.rxlab.guide
repo_url: https://github.com/RxLaboratory/OCA/
edit_uri: edit/master/src-docs/docs
site_description: The Open Cel Animation documentation
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2020-2023 RxLaboratory and Nicolas Dufresne'
use_directory_urls: false
theme:
    name: null
    custom_dir: 'cinder'
    colorscheme: zenburn
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - fenced_code
    - attr_list
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
    - meta.js
    - collapser.js
site_dir: ../docs/
dev_addr: '127.0.0.1:8001'
nav:
    - v1.2.0: index.md
    - Specifications:
        - Examples: specs/examples.md
        - Folder Structure: specs/folder-structure.md
        - File Specifications: specs/file.md
        - Objects:
            - Metadata JSON Object: specs/meta.md
            - Root JSON Object: specs/root.md
            - Layer JSON Object: specs/layer.md
            - Frame JSON Object: specs/frame.md
        - Values:
            - Durations: specs/durations.md
            - Coordinates and transform: specs/coordinates.md
            - Opacity, Colors and Color Depth: specs/color-depth.md
            - Layer Types: specs/layer-types.md
            - Blending Modes: specs/blending-modes.md
            - Layer Labels: specs/layer-labels.md
    - ...:
        - Roadmap: roadmap.md
        - Changelog: changelog.md
        - License:
            - GNU GPLv3: licenses/gnu-gpl.md
            - Documentation license: licenses/gfdl.md
        - Contact: http://contact.rxlab.info/
        - Donate: http://donate.rxlab.info/
